[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"


[tool.mypy]
show_error_codes = true
warn_unused_configs = true

# Disallow dynamic typing
#disallow_any_unimported = true
#disallow_any_expr = true
#disallow_any_decorated = true
#disallow_any_explicit = true
disallow_any_generics = true
#disallow_subclassing_any = true

# Untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
#disallow_untyped_decorators = true

# None and Optional handling
no_implicit_optional = true
strict_optional = true

# Configuring warnings
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

# Miscellaneous strictness flags
allow_untyped_globals = false
allow_redefinition = false
implicit_reexport = false
strict_equality = true


[tool.poe.tasks]
format = ["isort", "black"]
isort = "isort ."
black = "black ."

tests = ["test"]
test = ["isort_check", "black_check", "mypy", "pylint"]
isort_check = "isort . --check"
black_check = "black . --check"
mypy = "mypy useless_discord_bot"
pylint = "pylint useless_discord_bot --disable=fixme"


[tool.poetry]
name = "useless-discord-bot"
version = "0.1.0"
description = ""
authors = ["Parnassius <Parnassius@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "3.8.1"
cairosvg = "2.5.2"
disnake = "2.4.0"
environs = "9.5.0"
pillow = "9.0.1"

[tool.poetry.dev-dependencies]
black = "22.1.0"
isort = "5.10.0"
mypy = "0.931"
poethepoet = "0.13.1"
pylint = "2.13.2"

[tool.poetry.scripts]
bot = "useless_discord_bot.__main__:main"


[tool.pylint.master]
load-plugins = [
    "pylint.extensions.bad_builtin",
    "pylint.extensions.check_elif",
    "pylint.extensions.for_any_all",
    "pylint.extensions.typing",
]

[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",

    "too-many-locals",
    "too-many-statements",

    "consider-alternative-union-syntax",
]
enable = ["useless-suppression"]

[tool.pylint.format]
expected-line-ending-format = "LF"
max-line-length = "88"
