name: ci/cd

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
      - name: Run editorconfig-checker
        run: editorconfig-checker

  test:
    runs-on: ${{ matrix.arch.os }}
    strategy:
      matrix:
        arch:
          - name: amd64
            os: ubuntu-24.04  # renovate: github-runner
          - name: arm64
            os: ubuntu-24.04-arm  # renovate: github-runner
    steps:
      - uses: actions/checkout@v4
      - name: Lint and test in container
        run: podman build --platform linux/${{ matrix.arch.name }} --target test .

  publish:
    permissions:
      contents: read
      packages: write
    needs: [editorconfig, test]
    if: contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref_name == 'main'
    runs-on: ${{ matrix.arch.os }}
    strategy:
      matrix:
        arch:
          - name: amd64
            os: ubuntu-24.04  # renovate: github-runner
          - name: arm64
            os: ubuntu-24.04-arm  # renovate: github-runner
    steps:
      - uses: actions/checkout@v4
      - name: Get target image name
        id: image
        run: echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - name: Build image
        run: podman build --platform linux/${{ matrix.arch.name }} --tag ${{ steps.image.outputs.image_name }}:latest-${{ matrix.arch.name }} .
      - name: Push to ghcr.io
        run: podman push --creds=${{ github.actor }}:${{ github.token }} ${{ steps.image.outputs.image_name }}:latest-${{ matrix.arch.name }} ghcr.io/${{ steps.image.outputs.image_name }}:latest-${{ matrix.arch.name }}

  publish-multiarch:
    permissions:
      contents: read
      packages: write
    needs: publish
    runs-on: ubuntu-24.04
    steps:
      - name: Get target image name
        id: image
        run: echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - name: Create manifest
        run: podman manifest create ${{ steps.image.outputs.image_name }}:latest
      - name: Add images to the manifest
        run: |
          podman manifest add ${{ steps.image.outputs.image_name }}:latest ghcr.io/${{ steps.image.outputs.image_name }}:latest-amd64
          podman manifest add ${{ steps.image.outputs.image_name }}:latest ghcr.io/${{ steps.image.outputs.image_name }}:latest-arm64
      - name: Push to ghcr.io
        run: podman manifest push --creds=${{ github.actor }}:${{ github.token }} ${{ steps.image.outputs.image_name }}:latest ghcr.io/${{ steps.image.outputs.image_name }}:latest
      - name: Delete old image versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 10

  dummy-required-job:
    runs-on: ubuntu-24.04
    needs: [editorconfig, test]
    if: always()
    steps:
      - run: exit 1
        if: ${{ contains( needs.*.result, 'failure' ) || contains( needs.*.result, 'cancelled' ) }}
