name: main

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Cache Poetry virtualenv
      id: virtualenv-cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-
    - name: Install Poetry
      run: curl -fsS https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - -y
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies on a cache miss...
      if: steps.virtualenv-cache.outputs.cache-hit != 'true'
      run: make deps
    - name: ...or mark them as up-to-date on a cache hit
      if: steps.virtualenv-cache.outputs.cache-hit == 'true'
      run: make deps --touch
    - name: Check import order
      run: make isort_check
    - name: Check formatting using black
      run: make black_check
    - name: Test with mypy
      run: make mypy
    - name: Test with pylint
      run: make pylint
