name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies on a cache miss
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync
      - name: Check formatting with black
        run: poetry run poe black --check
      - name: Type check with mypy
        run: poetry run poe mypy
      - name: Lint with ruff
        run: poetry run poe ruff
